// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diwmlvtyaouwzozvvhnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpd21sdnR5YW91d3pvenZ2aG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzAyMzcsImV4cCI6MjA2NTg0NjIzN30.NApD-UAYpcJJ3CuSLiDINAcUfJuoAAYbOqK49jbFCI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});